### ISSUE TITLE
Bot will sometimes not display a gif

### ISSUE THREAD

**Issue by MirceaZisu** [Dragonsight91/Demon-Overlord#11]
Message Link to it happening: https://discordapp.com/channels/658407338822336554/658407339283447869/729018906752057406

Screenshot for easier access: https://prnt.sc/tbtb3u

When using -mao dance , the bot failed to provide a gif. Tested it again with a different song as I thought it may have been related to the song details, and then again with the same song. Was unable to replicate it. 

Unsure if there may be other instances of it happening yet.

**Comment by Dragonsight91** [comment]
Since this is a rare issue and doesn't affect usability that much, this won't be worked on.
If this happens more often, this will be considered, but for now, it is not a priority.
