### ISSUE TITLE
[TODO] GIFs can sometimes be quite terrible -> implement GIF pool

### ISSUE THREAD

**Issue by Dragonsight91** [Dragonsight91/Demon-Overlord#33]
there needs to be a GIF pool, to have more control over the gifs that are displayed on interactions. 
this should be done in the `DemonOverlord/config/special/interactions.json` file, by adding the property "gifs" with an array in each interaction, specifying a link of urls

**Comment by F0Xanne** [comment]
Working on making this GIF pool (10> for every interaction).
I will make a pull request when done.
Maybe takes a little time to finish the full pool, need to go through 1000's of gif's.

**Comment by Dragonsight91** [comment]
> Working on making this GIF pool (10> for every interaction).
> I will make a pull request when done.
> Maybe takes a little time to finish the full pool, need to go through 1000's of gif's.

sounds good, just send a PR when you're done
