### ISSUE TITLE
[BUGFIX] Rate limiter bug

### ISSUE THREAD

**Issue by F0Xanne** [Dragonsight91/Demon-Overlord#47]
Rate limiter counts up instead of down.
Code seems to need some fixing, and should count time remaining.

**Comment by Dragonsight91** [comment]
This is a known issue and there is a lot more bugs in that limiter than just that...

**Comment by Dragonsight91** [comment]
Conclusion is: ratelimiter needs to be rewritten and integrated with the database to allow custom per-command limits.

**Comment by Dragonsight91** [comment]
> Conclusion is: ratelimiter needs to be rewritten and integrated with the database to allow custom per-command limits.

The ratelimiter parts have been temporarily removed to later be rewritten
