### ISSUE TITLE
[TODO] Database interaction needs to be redone

### ISSUE THREAD

**Issue by Dragonsight91** [Dragonsight91/Demon-Overlord#70]
Currently the database is based off an internal template in `DemonOverlord/config/db_template.json` which is a good thing, but the bot seems to have trouble setting it up and correcting its own mistakes. The complete interaction with the database would also need need to be revamped and should be made async with [asyncpg](https://github.com/MagicStack/asyncpg).

The whole code base the way it is now also seems sort of clunky in its configuration and this Database integration problem is related to #66 and a proper custom interface should be made for the database to handle caching and writing to the database.

**Comment by NattCaat** [comment]
Closed due to necessity to rewrite the bot
